<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5e73bded784bb',
	'title' => 'Coronavirus',
	'fields' => array(
		array(
			'key' => 'field_5e73be00ea2ec',
			'label' => 'Test Kits Available?',
			'name' => 'coronavirus_test_kits_available',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e73be00ea2ed',
			'label' => 'Coronavirus Current Testing Hours',
			'name' => 'coronavirus_testing_hours_today',
			'type' => 'text',
			'instructions' => 'To use more granular weekly testing schedule, leave hours blank and fields will appear.  Note: Leave hours blank for banner to say "Available today!". Be sure to remove any weekly schedule hours from below as well.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),

		array(
			'key' => 'field_5f201f95b2d9f',
			'label' => 'Coronavirus Current Weekly Hours',
			'name' => 'coronavirus_current_weekly_hours',
			'type' => 'repeater',
			'instructions' => 'Add weekly testing hours. If there is one set time, choose "Everyday" and only add one set of times. If there is no testing on a day, do not add that day to schedule.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e73be00ea2ed',
						'operator' => '==empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 7,
			'layout' => 'row',
			'button_label' => 'Add Block',
			'sub_fields' => array(
				array(
					'key' => 'field_5f201fd0b2da0',
					'label' => 'Weekday',
					'name' => 'weekday',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'all' => 'Everyday',
						'mon' => 'Monday',
						'tues' => 'Tuesday',
						'wed' => 'Wednesday',
						'thurs' => 'Thursday',
						'fri' => 'Friday',
						'sat' => 'Saturday',
						'sun' => 'Sunday',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5f202049b2da1',
					'label' => 'Hours',
					'name' => 'hours',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 1,
					'max' => 1,
					'layout' => 'table',
					'button_label' => 'Add Hours',
					'sub_fields' => array(
						array(
							'key' => 'field_5f202090b2da2',
							'label' => 'Start',
							'name' => 'start',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'g:i a',
							'return_format' => 'g:i A',
						),
						array(
							'key' => 'field_5f2020c7b2da3',
							'label' => 'End',
							'name' => 'end',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'g:i a',
							'return_format' => 'g:i A',
						),
					),
				),
			),
		),

		array(
			'key' => 'field_5e824174dbb8c',
			'label' => 'Weekly Testing Hours Text',
			'name' => 'coronavirus_weekly_testing_hours_text',
			'type' => 'text',
			'instructions' => 'Add text about testing hours for the week in a readable text. Ex: "Mon - Thurs from 9AM - 9PM"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e824174dbb8d',
			'label' => 'Pre-Registration Required?',
			'name' => 'coronavirus_preregistration_required',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'locations',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
